<../../mkconfig

TARG=\
	irc.dis\

SYSMODULES=\
	arg.m\
	bufio.m\
	daytime.m\
	draw.m\
	keyboard.m\
	keyring.m\
	regex.m\
	plumbmsg.m\
	string.m\
	sys.m\
	tk.m\
	tkclient.m\

DISBIN=$ROOT/dis/wm

<$ROOT/mkfiles/mkdis
