<../../mkconfig

TARG=\
	testirc.dis\
	ircfs.dis\

SYSMODULES=\
	arg.m\
	bufio.m\
	daytime.m\
	draw.m\
	keyring.m\
	lists.m\
	string.m\
	styx.m\
	styxservers.m\
	sys.m\
	irc.m\

DISBIN=$ROOT/dis

<$ROOT/mkfiles/mkdis
